### ISSUE TITLE
Diversity Modifier doesn't work with custom classes

### ISSUE THREAD

**Issue by fiiiiilth** [daviscook477/CustomClimb#1]
Playing as Ironclad/Silent with the Diversity modifier doesn't give cards belonging to custom classes.

Playing as a custom class, it doesn't give you any cards.

**Comment by Downanddirty4568** [comment]
Thats because this custom climb mod, does not change what the modifier does it only allows you to choose the modifiers and since the regular Diversity Modifier would not give you cards from, The juggernaut, or any of the modded characters, that would be why it does not work because the custom climb mod is not intended to change the modifiers from what they originally are in the base game.
