### ISSUE TITLE
Certain modifiers do not work at all

### ISSUE THREAD

**Issue by Downanddirty4568** [daviscook477/CustomClimb#9]
The modifiers: Vintage and insanity and there was like a couple others but i cant remember which ones they were, do not work for me no matter what i have the latest version of ModTheSpire, downloaded everything as instructed, i even tried a later version of ModTheSpire and they still do not work, ill put Vintage as a modifier, the enemies still give me cards instead of relics, and i put insanity and i very well start with the regular deck, at first i thought it was only not working for the modded characters because they have special decks, but nope it doesn't work for the ironclad or The Silent either.

**Comment by spedrickson** [comment]
Experiencing same issue

BaseMod week 20 patch
v2.6.0 ModTheSpire
v0.3.1 CustomClimb

Went through and started an Ironclad run with each modifier individually. Here are the results:

vintage: broken
time dilation: broken
insanity: broken

big game hunter: seems to work?
lethality: works
heirloom: works
certain future: works
binary: works
night terrors: works
terminal: works
hoarder: works
draft: works
diverse: works
all star: works
shiny: works
midas: works
cursed run: works

**Comment by Downanddirty4568** [comment]
i really hope they will fix this because this is honestly one of my favorite mods if not my favorite mod.

**Comment by daviscook477** [comment]
I think this issue is the same underlying cause as #8. Closing as duplicate for now.

Thank you so much for the report of which mods are broken. It helped me figure out what was going on. Basically the devs reclassified those mods as positive or negative when they used to be the opposite but they only reclassified them in one location but the game tracks which mods are positive and which are negative in two places. Really weird but it'll be fixed in a new version of CustomClimb.
